### PR TITLE
refactor odom example

### PR DESCRIPTION
**Pull request by mikeferguson**
* revert to class based approach
* add proper license

### CODE REVIEW

**Comment by mikeferguson** [comment]
This shouldn't be merged until we actually test on the robot next week.

**Comment by KenwoodFox** [comment]
Thank you so much mike, the code looks amazing, what license is that though? Are nonprofits an inc?

**Review by KenwoodFox — APPROVED** [review]
apart from the error in including flakeEncoder.py.save, its good to go

**Review by KenwoodFox — APPROVED** [review]

**Review by KhanSimeoni — APPROVED** [review]

**Comment by KenwoodFox** [comment]
image
It works!

**Pull request merged**
